import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className='d-flex'>
          <a href='/fonct' className='link'>
            Fonctionnalité camera
          </a>
          <a href='/add' className='link'>
            Fonctionnalité add
          </a>
          <a href='/zoom' className='link'>
            Fonctionnalité zoom
          </a>
        </div>
      </main>
    </>
  );
}
