import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className='d-flex'>
          <a href='/qrCode' className='link'>
            Fonctionnalité Qr Code Scanner
          </a>
          {/* <a href='/codeBar' className='link'>
            Fonctionnalité CodeBar Scanner
          </a> */}
          <a href='/add' className='link'>
            Fonctionnalité add
          </a>
          <a href='/generate' className='link'>
            Fonctionnalité generate Qr Code
          </a>
        </div>
      </main>
    </>
  );
}
